<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>p3dx</name>
  <version>0.0.0</version>
  <description>TODO: Package description</description>
  <maintainer email="gerard@todo.todo">gerard</maintainer>
  <license>TODO: License declaration</license>



  <depend>xacro</depend>
  <depend>ros_gz_sim</depend>
  <depend>ros_gz_bridge</depend>
  <depend>tf2_ros</depend>
  <depend>rviz2</depend>

  <depend>slam_toolbox</depend>
  <depend>nav2_bringup</depend>
  <depend>nav2_simple_commander</depend>


  <export>
    <build_type>ament_cmake</build_type>
  </export>

</package>
