; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html



[env:esp32-s3-wroom-wifi]
platform = espressif32
board = esp32-s3-devkitc-1
;board = esp32-s3-devkitc-1-n16r8v
framework = arduino

board_build.filesystem = spiffs  ; Changed from littlefs

;board_build.psram = disabled
board_build.partitions = default_8MB.csv
board_build.memory_type = qio_opi
monitor_speed = 115200


lib_deps =
;    https://github.com/micro-ROS/micro_ros_platformio
;    https://github.com/nicolas-beaufort/micro_ros_platformio
    https://github.com/AvansMechatronica/micro_ros_platformio
    WiFi
;    ottowinter/ESPAsyncWebServer-esphome@^3.3.0
    ESP32Async/ESPAsyncWebServer
    adafruit/Adafruit ST7735 and ST7789 Library@^1.10.3
;    jrowberg/I2Cdevlib-MPU6050@^1.0.0
;    jrowberg/I2Cdevlib-Core@^1.0.1
    https://github.com/electroniccats/mpu6050.git
    


build_flags = 
  -DWIFI
  -DWIFI_INCLUDE_TFT_PRINT
  -DDEBUG
  -DHANDLE_BUMPERS
  -DINCLUDE_LIDAR
  -DLIDAR_INVERT_SCAN
  -DLIDAR_ANGLE_OFFSET=-90
  -DUSE_SPIFFS
  -DCORE_DEBUG_LEVEL=5
;  -DARDUINO_ESP32S3_DEV
;  -DBOARD_HAS_PSRAM
;  -DARDUINO_USB_MODE=1
;  -DARDUINO_USB_CDC_ON_BOOT=1

board_microros_transport = wifi
monitor_filters = esp32_exception_decoder

; Force erase flash on upload to fix filesystem
; Run manually if needed: pio run -t erase
;upload_flags = 
;  --erase-flash

[env:esp32-s3-wroom-usb]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
lib_deps =
;    https://github.com/micro-ROS/micro_ros_platformio
;    https://github.com/nicolas-beaufort/micro_ros_platformio
    https://github.com/AvansMechatronica/micro_ros_platformio
    adafruit/Adafruit ST7735 and ST7789 Library@^1.10.3

build_flags =
;    -DHANDLE_BUMPERS
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DINCLUDE_IMU
    -DLIDAR_INVERT_SCAN
    -DLIDAR_ANGLE_OFFSET=90


board_microros_transport = serial