; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[platformio]
default_envs = esp32-s3-wroom-wifi

[env:esp32-s3-wroom-wifi]
platform = espressif32
;board = esp32-s3-devkitc-1-n16r8v ;This configuration is for the ESP32-S3-DevKitC-1 with 16MB flash and 8MB PSRAM,
;board = esp32-s3-devkitc-1
board = esp32-s3-devkitc-1
framework = arduino

board_upload.flash_size = 8MB
board_build.partitions = partitions_8mb_small_lfs.csv
board_build.filesystem = littlefs
board_build.psram = disabled

;board_upload.flash_size = 8MB
;board_build.partitions = default_8MB.csv
;board_build.filesystem = littlefs

monitor_speed = 115200

lib_deps =
    https://github.com/AvansMechatronica/micro_ros_platformio
    WiFi
    ESP32Async/ESPAsyncWebServer
    adafruit/Adafruit ST7735 and ST7789 Library@^1.10.3
    https://github.com/electroniccats/mpu6050.git
    

build_flags = 
; Enable WiFi
  -DWIFI 
; Enable WiFi config debug
  -DNETWORK_CONFIG_DEBUG
; Enable native USB CDC serial on ESP32-S3, do not change this when using WiFi transport for micro-ROS 
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
; Enable TFT print for WiFi status
  -DWIFI_INCLUDE_TFT_PRINT
; Enable general debugging
;  -DDEBUG 
; Enable motor controller debug
;  -DDEBUG_MOTOR_CONTROLLER 
; Detach encoder interrupts during critical sections to prevent issues with the ESP32-S3's USB CDC implementation, use with caution as it may cause missed encoder ticks
; -DDE_ATTACH_ENCODER_INTERRUPTS
; Enable multiple executors for publishers
  -DMULTIPLE_PUBLISH_EXECUTORS
; Enable bumper handling 
  -DHANDLE_BUMPERS 
; Enable LIDAR
  -DINCLUDE_LIDAR
; Lidar type, choose one of the following based on your hardware
;  -DLIDAR_RP
;  -DLIDAR_LDS08
; LIDAR angle offset for LDS-08, adjust as needed for your specific mounting orientation
;  -DLIDAR_ANGLE_OFFSET=-90 
; Invert LIDAR scan for LDS-08, adjust as needed based on your specific mounting orientation and desired scan direction
;  -DLIDAR_INVERT_SCAN 
  -DLIDAR_YD_T_MINI
; LiDAR angle offset for YDLIDAR T-mini Plus, adjust as needed for your specific mounting orientation
  -DLIDAR_ANGLE_OFFSET=180
; Invert LIDAR scan for YDLIDAR T-mini Plus, adjust as needed based on your specific mounting orientation and desired scan direction  
  -DLIDAR_INVERT_SCAN 
; Enable LIDAR debug
;  -DDEBUG_LIDAR
; Set core debug level to maximum
 -DCORE_DEBUG_LEVEL=3
; Enable IMU not tested yet, use with caution
;  -DINCLUDE_IMU 
; Enable IMU debug
;  -DDEBUG_IMU
; Enable IMU acquisition debug
;  -DDEBUG_IMU_AQUISITION


; Use WiFi transport for micro-ROS
board_microros_transport = wifi 
; Decode exceptions
;monitor_filters = esp32_exception_decoder 


[env:esp32-s3-wroom-usb]
platform = espressif32
board = esp32-s3-devkitc-1-n16r8v
framework = arduino

board_upload.flash_size = 8MB
board_build.partitions = default_8MB.csv
monitor_speed = 115200

lib_deps =
    https://github.com/AvansMechatronica/micro_ros_platformio
    adafruit/Adafruit ST7735 and ST7789 Library@^1.10.3
    https://github.com/electroniccats/mpu6050.git
    

build_flags = 
; Enable native USB CDC serial on ESP32-S3
;  -DARDUINO_USB_MODE=1
;  -DARDUINO_USB_CDC_ON_BOOT=1
; Enable general debugging
;  -DDEBUG 
; Enable motor controller debug
;  -DDEBUG_MOTOR_CONTROLLER 
; Enable multiple executors for publishers
  -DMULTIPLE_PUBLISH_EXECUTORS
; Enable bumper handling 
  -DHANDLE_BUMPERS 
; Enable LIDAR
  -DINCLUDE_LIDAR
; Enable LIDAR debug
;  -DDEBUG_LIDAR
; Invert LIDAR scan
  -DLIDAR_INVERT_SCAN 
; LIDAR angle offset
  -DLIDAR_ANGLE_OFFSET=-90 
; Set core debug level to maximum
; -DCORE_DEBUG_LEVEL=5
; Enable IMU
  -DINCLUDE_IMU
; Enable IMU debug
;  -DDEBUG_IMU
; Enable IMU acquisition debug
;  -DDEBUG_IMU_AQUISITION

board_microros_transport = serial
