; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:eps32-upesy_wroom]
platform = espressif32
board = upesy_wroom
framework = arduino


monitor_speed = 115200
lib_deps =
;    https://github.com/micro-ROS/micro_ros_platformio
;    https://github.com/nicolas-beaufort/micro_ros_platformio
    https://github.com/AvansMechatronica/micro_ros_platformio
    adafruit/Adafruit ST7735 and ST7789 Library@^1.10.3


build_flags =
;    -DHANDLE_BUMPERS


board_microros_transport = serial

[env:eps32-upesy_wroom-wifi]
platform = espressif32
board = upesy_wroom
framework = arduino

board_build.filesystem = littlefs

monitor_speed = 115200
lib_deps =
;    https://github.com/micro-ROS/micro_ros_platformio
;    https://github.com/nicolas-beaufort/micro_ros_platformio
    https://github.com/AvansMechatronica/micro_ros_platformio
    WiFi
    ottowinter/ESPAsyncWebServer-esphome@^3.3.0
;    ESP32Async/ESPAsyncWebServer
    adafruit/Adafruit ST7735 and ST7789 Library@^1.10.3

build_flags = 
  -DWIFI
  -D WIFI_SSID='"Wifi_ssid"'
  -D WIFI_PASSWORD='"Wifi_Password"'
  -DAGENT_IP_ADDRESS={192,168,0,100}
  -DPORT=8888
;  -DHANDLE_BUMPERS

board_microros_transport = wifi

