teleop_twist_joy_node:
  ros__parameters:
    require_enable_button: true
    enable_button: 5  # RB button on F710 gamepad

    axis_linear:
      x: 1  # Left joystick up/down


    scale_linear:
      x: 1.0 # m/s per unit of joystick input
      y: 1.0 # m/s per unit of joystick input

    axis_angular:
      yaw: 0  # Left joystick left/right

    scale_angular:
      yaw: 1.0 # rad/s per unit of joystick input