teleop_twist_joy_node:
  ros__parameters:
    require_enable_button: true
    enable_button: 4  # LB button on F710 gamepad

    axis_linear:
      x: 4  # Right joystick up/down

    scale_linear:
      x: 0.5
      y: 0.5

    axis_angular:
      yaw: 3  # Right joystick left/right

    scale_angular:
      yaw: 1.0